// Package glyphs maps Adobe Glyph List and related names to Unicode
// characters.
//
// Port of pdf-inspector v1.14.2 src/glyph_names.rs. The name→rune table lives
// in tables.go, generated by tools/tablegen.
package glyphs

import (
	"strconv"
	"strings"
)

// BuildGlyphToUnicodeMap returns a fresh copy of the Adobe Glyph List (AGL)
// name→Unicode map. The returned map is owned by the caller.
//
// Upstream: pub fn build_glyph_to_unicode_map() -> HashMap<&'static str, char>.
func BuildGlyphToUnicodeMap() map[string]rune {
	m := make(map[string]rune, len(glyphTable))
	for k, v := range glyphTable {
		m[k] = v
	}
	return m
}

// glyphToUnicode mirrors the upstream GLYPH_TO_UNICODE LazyLock: the AGL table
// plus local overrides for non-standard glyph names seen in PDFs.
var glyphToUnicode = func() map[string]rune {
	m := BuildGlyphToUnicodeMap()
	for k, v := range glyphOverrides {
		m[k] = v
	}
	return m
}()

// GlyphToChar converts a glyph name to its Unicode character.
//
// Resolution order: exact name; base name before a '.' suffix (per the AGL
// spec, e.g. "zero.tf" → "zero"); uniXXXX (with the Windows Symbol PUA F000
// offset stripped); uXXXX / uXXXXX.
//
// Upstream: pub fn glyph_to_char(name: &str) -> Option<char>.
func GlyphToChar(name string) (rune, bool) {
	// First check our mapping with the full name.
	if c, ok := glyphToUnicode[name]; ok {
		return c, true
	}

	// Per Adobe Glyph List spec, strip the suffix after '.' to get the base
	// glyph name. E.g., "zero.tf" → "zero", "a.ss01" → "a", "hyphen.case" →
	// "hyphen". ('.' is ASCII, so the byte index is always a char boundary.)
	if dot := strings.IndexByte(name, '.'); dot >= 0 {
		if c, ok := glyphToUnicode[name[:dot]]; ok {
			return c, true
		}
	}

	// Try to parse uniXXXX format. `name` can contain non-ASCII runes (e.g.
	// U+FFFD from lossy UTF-8 decoding of an attacker controlled /Differences
	// name), so slice on rune boundaries: only take the prefix when the first
	// four runes exist (upstream rest.get(..4)).
	if rest, ok := strings.CutPrefix(name, "uni"); ok {
		if hex, ok := firstRunes(rest, 4); ok {
			if code, ok := rustParseUint(hex, 16, 32); ok {
				// Strip PUA F000 offset: uniF0XX → U+00XX
				// (Windows Symbol encoding convention).
				if code >= 0xF000 && code <= 0xF0FF {
					code -= 0xF000
				}
				return charFromU32(code)
			}
		}
	}

	// Try to parse uXXXX or uXXXXX format.
	if len(name) >= 5 && name[0] == 'u' {
		if code, ok := rustParseUint(name[1:], 16, 32); ok {
			return charFromU32(code)
		}
	}

	return 0, false
}

// firstRunes returns the first n runes of s as a string, reporting false when
// s has fewer than n runes. This mirrors Rust's str::get(..n) boundary check.
func firstRunes(s string, n int) (string, bool) {
	count := 0
	for i := range s {
		if count == n {
			return s[:i], true
		}
		count++
	}
	if count == n {
		return s, true
	}
	return "", false
}

// rustParseUint parses like Rust's from_str_radix: an optional leading '+' is
// accepted, no other sign, no underscores, no base prefix. Digits outside the
// base or overflow report false.
func rustParseUint(s string, base, bits int) (uint32, bool) {
	s = strings.TrimPrefix(s, "+")
	v, err := strconv.ParseUint(s, base, bits)
	if err != nil {
		return 0, false
	}
	return uint32(v), true
}

// charFromU32 mirrors Rust's char::from_u32: false for surrogates and anything
// above the Unicode maximum.
func charFromU32(cp uint32) (rune, bool) {
	if cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF) {
		return 0, false
	}
	return rune(cp), true
}
