// Command tablegen regenerates the Go data tables used by the pdf engine's
// font packages from the pinned upstream Rust sources (pdf-inspector v1.14.2).
//
// # Regeneration command
//
// From the module root:
//
//	go run ./tools/tablegen -upstream /tmp/upstream/pdf-inspector
//
// -upstream must point at a checkout of pdf-inspector v1.14.2 (the frozen
// upstream reference). -out is the module root to write into (default ".").
//
// The tool reads:
//
//	src/glyph_names.rs      -> pdf/internal/glyphs/tables.go
//	src/adobe_korea1.rs     -> pdf/internal/korea1/tables.go
//	src/structure_tree.rs   -> pdf/internal/structuretree/tables.go
//	external/bcmaps/*.bcmap -> pdf/internal/tounicode/bcmaps/
//
// Output is deterministic and byte-stable: rerunning against the same upstream
// tree produces identical files (generated sources are gofmt-formatted with
// go/format before being written).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode/utf8"
)

func main() {
	upstream := flag.String("upstream", "/tmp/upstream/pdf-inspector", "path to the pdf-inspector v1.14.2 checkout")
	out := flag.String("out", ".", "module root to write generated files into")
	flag.Parse()

	if err := run(*upstream, *out); err != nil {
		log.Fatal(err)
	}
}

func run(upstream, out string) error {
	if err := genGlyphs(filepath.Join(upstream, "src", "glyph_names.rs"), filepath.Join(out, "pdf", "internal", "glyphs", "tables.go")); err != nil {
		return err
	}
	if err := genKorea1(filepath.Join(upstream, "src", "adobe_korea1.rs"), filepath.Join(out, "pdf", "internal", "korea1", "tables.go")); err != nil {
		return err
	}
	if err := genStructureTree(filepath.Join(upstream, "src", "structure_tree.rs"), filepath.Join(out, "pdf", "internal", "structuretree", "tables.go")); err != nil {
		return err
	}
	if err := copyBcmaps(filepath.Join(upstream, "external", "bcmaps"), filepath.Join(out, "pdf", "internal", "tounicode", "bcmaps")); err != nil {
		return err
	}
	return nil
}

const generatedHeader = "// Code generated by tools/tablegen from pdf-inspector v1.14.2 %s. DO NOT EDIT."

// ─── glyph_names.rs ──────────────────────────────────────────────────────────

var glyphInsertRe = regexp.MustCompile(`^\s*m\.insert\("((?:[^"\\]|\\.)*)", ('(?:[^'\\]|\\.)+'|'\\u\{[0-9A-Fa-f]+\}')\);`)

func genGlyphs(src, dst string) error {
	lines, err := readLines(src)
	if err != nil {
		return err
	}

	// Inserts before the GLYPH_TO_UNICODE static belong to
	// build_glyph_to_unicode_map (the base AGL table); inserts after it are the
	// LazyLock closure's local overrides.
	seenStatic := false
	var base, overrides [][2]string // (name, Go rune literal source)
	for _, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "static GLYPH_TO_UNICODE") {
			seenStatic = true
			continue
		}
		m := glyphInsertRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		key, err := unquoteRustString(m[1])
		if err != nil {
			return fmt.Errorf("%s: bad glyph name %q: %w", src, m[1], err)
		}
		r, err := parseRustCharLit(m[2])
		if err != nil {
			return fmt.Errorf("%s: bad char literal %s: %w", src, m[2], err)
		}
		entry := [2]string{strconv.Quote(key), goRuneLit(r)}
		if seenStatic {
			overrides = append(overrides, entry)
		} else {
			base = append(base, entry)
		}
	}
	if len(base) == 0 || len(overrides) == 0 {
		return fmt.Errorf("%s: expected base inserts and GLYPH_TO_UNICODE overrides, got %d/%d", src, len(base), len(overrides))
	}

	var b strings.Builder
	fmt.Fprintf(&b, generatedHeader+"\n\n", "src/glyph_names.rs")
	b.WriteString("package glyphs\n\n")
	fmt.Fprintf(&b, "// glyphTable is the Adobe Glyph List (and related names) extracted from the\n// upstream build_glyph_to_unicode_map() body (%d entries).\nvar glyphTable = map[string]rune{\n", len(base))
	writeEntries(&b, base)
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "// glyphOverrides are local overrides for non-standard glyph names seen in\n// PDFs, applied on top of glyphTable by the GLYPH_TO_UNICODE LazyLock (%d entries).\nvar glyphOverrides = map[string]rune{\n", len(overrides))
	writeEntries(&b, overrides)
	b.WriteString("}\n")
	return writeFormatted(dst, []byte(b.String()))
}

func writeEntries(b *strings.Builder, entries [][2]string) {
	for _, e := range entries {
		fmt.Fprintf(b, "\t%s: %s,\n", e[0], e[1])
	}
}

// unquoteRustString resolves the escape sequences that appear in the upstream
// glyph-name string literals.
func unquoteRustString(s string) (string, error) {
	if !strings.Contains(s, `\`) {
		return s, nil
	}
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		if s[i] != '\\' {
			b.WriteByte(s[i])
			continue
		}
		i++
		if i >= len(s) {
			return "", fmt.Errorf("trailing backslash")
		}
		switch s[i] {
		case '\\', '"':
			b.WriteByte(s[i])
		case 'n':
			b.WriteByte('\n')
		case 'r':
			b.WriteByte('\r')
		case 't':
			b.WriteByte('\t')
		case '0':
			b.WriteByte(0)
		default:
			return "", fmt.Errorf("unsupported escape \\%c", s[i])
		}
	}
	return b.String(), nil
}

// parseRustCharLit parses a Rust character literal ('A', '\u{202C}', '\x0C',
// '\r', '\\', ...), quotes included, into a rune.
func parseRustCharLit(lit string) (rune, error) {
	if len(lit) < 3 || lit[0] != '\'' || lit[len(lit)-1] != '\'' {
		return 0, fmt.Errorf("not a char literal: %s", lit)
	}
	body := lit[1 : len(lit)-1]
	if !strings.HasPrefix(body, `\`) {
		r, size := utf8.DecodeRuneInString(body)
		if size != len(body) || len(body) != 1 && size != len(body) {
			return 0, fmt.Errorf("not a single char: %s", lit)
		}
		return r, nil
	}
	esc := body[1:]
	switch esc {
	case "\\":
		return '\\', nil
	case "'":
		return '\'', nil
	case "\"":
		return '"', nil
	case "n":
		return '\n', nil
	case "r":
		return '\r', nil
	case "t":
		return '\t', nil
	case "0":
		return 0, nil
	}
	switch {
	case esc == "n":
		return '\n', nil
	case esc == "r":
		return '\r', nil
	case esc == "t":
		return '\t', nil
	case esc == "0":
		return 0, nil
	case strings.HasPrefix(esc, "x"):
		v, err := strconv.ParseUint(esc[1:], 16, 8)
		if err != nil {
			return 0, err
		}
		return rune(v), nil
	case strings.HasPrefix(esc, "u{") && strings.HasSuffix(esc, "}"):
		v, err := strconv.ParseUint(esc[2:len(esc)-1], 16, 32)
		if err != nil {
			return 0, err
		}
		return rune(v), nil
	default:
		return 0, fmt.Errorf("unsupported escape %s", esc)
	}
}

// goRuneLit renders a rune as a Go rune literal. Printable runes are emitted
// verbatim (UTF-8 source); control runes and quotes are escaped. The mapping
// depends only on the code point, so regeneration is byte-stable.
func goRuneLit(r rune) string {
	switch {
	case r == '\'':
		return `'\''`
	case r == '\\':
		return `'\\'`
	case r < 0x20 || r == 0x7F:
		return fmt.Sprintf("'\\x%02x'", r)
	case r == 0xFEFF:
		// A byte order mark is only legal at the very start of a Go file; the
		// scanner rejects it inside a rune literal.
		return "'\\uFEFF'"
	default:
		return "'" + string(r) + "'"
	}
}

// ─── adobe_korea1.rs ─────────────────────────────────────────────────────────

var korea1RowRe = regexp.MustCompile(`^\s*\((\d+),\s*(0x[0-9A-Fa-f]+|\d+)\),$`)

func genKorea1(src, dst string) error {
	lines, err := readLines(src)
	if err != nil {
		return err
	}
	var rows []string
	for _, line := range lines {
		m := korea1RowRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		cid, err := strconv.ParseUint(m[1], 10, 16)
		if err != nil {
			return fmt.Errorf("%s: bad CID %q: %w", src, m[1], err)
		}
		uni, err := strconv.ParseUint(m[2], 0, 16)
		if err != nil {
			return fmt.Errorf("%s: bad Unicode %q: %w", src, m[2], err)
		}
		rows = append(rows, fmt.Sprintf("\t{%d, 0x%04X},", cid, uni))
	}
	if len(rows) == 0 {
		return fmt.Errorf("%s: no table rows found", src)
	}

	var b strings.Builder
	fmt.Fprintf(&b, generatedHeader+"\n\n", "src/adobe_korea1.rs")
	b.WriteString("package korea1\n\n")
	fmt.Fprintf(&b, "// AdobeKorea1CidToUnicode is the Adobe-Korea1 CID→Unicode mapping\n// (%d entries), sorted by CID for binary search.\n// Upstream: pub static ADOBE_KOREA1_CID_TO_UNICODE: &[(u16, u16)].\nvar AdobeKorea1CidToUnicode = [][2]uint16{\n", len(rows))
	for _, row := range rows {
		b.WriteString(row + "\n")
	}
	b.WriteString("}\n")
	return writeFormatted(dst, []byte(b.String()))
}

// ─── structure_tree.rs ────────────────────────────────────────────────────────

// knownNameRe matches a KNOWN_NAMES entry: b"Document",
var knownNameRe = regexp.MustCompile(`^b"((?:[^"\\]|\\.)*)",$`)

func genStructureTree(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	text := string(data)
	const marker = "const KNOWN_NAMES: &[&[u8]] = &["
	start := strings.Index(text, marker)
	if start < 0 {
		return fmt.Errorf("%s: KNOWN_NAMES not found", src)
	}
	rest := text[start+len(marker):]
	end := strings.Index(rest, "];")
	if end < 0 {
		return fmt.Errorf("%s: KNOWN_NAMES not terminated", src)
	}
	block := rest[:end]

	var names []string
	for _, line := range strings.Split(block, "\n") {
		line = strings.TrimSpace(line)
		m := knownNameRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		name, err := unquoteRustString(m[1])
		if err != nil {
			return fmt.Errorf("%s: bad name %q: %w", src, line, err)
		}
		names = append(names, name)
	}
	if len(names) == 0 {
		return fmt.Errorf("%s: no KNOWN_NAMES entries", src)
	}

	var b strings.Builder
	fmt.Fprintf(&b, generatedHeader+"\n\n", "src/structure_tree.rs")
	b.WriteString("package structuretree\n\n")
	fmt.Fprintf(&b, "// knownStructNames lists the known struct type names that may appear as bare\n// tokens in malformed /S entries (%d entries).\n// Upstream: const KNOWN_NAMES: &[&[u8]] in fix_bare_struct_names.\nvar knownStructNames = [][]byte{\n", len(names))
	for _, name := range names {
		fmt.Fprintf(&b, "\t[]byte(%s),\n", strconv.Quote(name))
	}
	b.WriteString("}\n")
	return writeFormatted(dst, []byte(b.String()))
}

// ─── external/bcmaps ──────────────────────────────────────────────────────────

func copyBcmaps(srcDir, dstDir string) error {
	entries, err := os.ReadDir(srcDir)
	if err != nil {
		return err
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		// The directory ships the pdf.js bcmaps plus their LICENSE; vendor both.
		if !strings.HasSuffix(e.Name(), ".bcmap") && e.Name() != "LICENSE" {
			continue
		}
		names = append(names, e.Name())
	}
	sort.Strings(names)
	if len(names) == 0 {
		return fmt.Errorf("%s: no .bcmap files", srcDir)
	}
	if err := os.MkdirAll(dstDir, 0o755); err != nil {
		return err
	}
	for _, name := range names {
		data, err := os.ReadFile(filepath.Join(srcDir, name))
		if err != nil {
			return err
		}
		if err := writeFileIfChanged(filepath.Join(dstDir, name), data); err != nil {
			return err
		}
	}
	return nil
}

// ─── helpers ──────────────────────────────────────────────────────────────────

func readLines(path string) ([]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return strings.Split(string(data), "\n"), nil
}

func writeFormatted(dst string, src []byte) error {
	formatted, err := format.Source(src)
	if err != nil {
		return fmt.Errorf("%s: generated source does not gofmt: %w\n%s", dst, err, src)
	}
	return writeFileIfChanged(dst, formatted)
}

func writeFileIfChanged(dst string, data []byte) error {
	if old, err := os.ReadFile(dst); err == nil && bytes.Equal(old, data) {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	return os.WriteFile(dst, data, 0o644)
}
