// Package korea1 provides the Adobe-Korea1 CID-to-Unicode mapping.
//
// Port of pdf-inspector v1.14.2 src/adobe_korea1.rs. The table lives in
// tables.go, generated by tools/tablegen (source: adobe-type-tools/cmap-resources
// Adobe-Korea1-2/cid2code.txt, UniKS-UCS2 column, first mapping per CID).
package korea1

import "sort"

// LookupKorea1 looks up a CID in the Adobe-Korea1 table and returns the
// Unicode character.
//
// Upstream: pub fn lookup_korea1(cid: u16) -> Option<char>.
func LookupKorea1(cid uint16) (rune, bool) {
	// binary_search_by_key over the CID column.
	idx := sort.Search(len(AdobeKorea1CidToUnicode), func(i int) bool {
		return AdobeKorea1CidToUnicode[i][0] >= cid
	})
	if idx < len(AdobeKorea1CidToUnicode) && AdobeKorea1CidToUnicode[idx][0] == cid {
		// char::from_u32: rejects surrogates and out-of-range values.
		cp := uint32(AdobeKorea1CidToUnicode[idx][1])
		if cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF) {
			return 0, false
		}
		return rune(cp), true
	}
	return 0, false
}
